"""A curated offline voice list.

The app normally downloads the full catalogue (300+ voices) from Microsoft on
first run and caches it. This list is only the safety net for when that call
fails - it still covers every major language plus a wide spread of English
and Indian-language voices.

Each entry: (ShortName, Gender, Locale, Human label)
"""

FALLBACK_VOICES = [
    # ---- English (US) ----
    ("en-US-AvaMultilingualNeural", "Female", "en-US", "Ava"),
    ("en-US-AndrewMultilingualNeural", "Male", "en-US", "Andrew"),
    ("en-US-EmmaMultilingualNeural", "Female", "en-US", "Emma"),
    ("en-US-BrianMultilingualNeural", "Male", "en-US", "Brian"),
    ("en-US-AriaNeural", "Female", "en-US", "Aria"),
    ("en-US-JennyNeural", "Female", "en-US", "Jenny"),
    ("en-US-GuyNeural", "Male", "en-US", "Guy"),
    ("en-US-MichelleNeural", "Female", "en-US", "Michelle"),
    ("en-US-ChristopherNeural", "Male", "en-US", "Christopher"),
    ("en-US-EricNeural", "Male", "en-US", "Eric"),
    ("en-US-RogerNeural", "Male", "en-US", "Roger"),
    ("en-US-SteffanNeural", "Male", "en-US", "Steffan"),
    ("en-US-AnaNeural", "Female", "en-US", "Ana (child)"),
    # ---- English (rest of the world) ----
    ("en-GB-SoniaNeural", "Female", "en-GB", "Sonia"),
    ("en-GB-RyanNeural", "Male", "en-GB", "Ryan"),
    ("en-GB-LibbyNeural", "Female", "en-GB", "Libby"),
    ("en-GB-ThomasNeural", "Male", "en-GB", "Thomas"),
    ("en-GB-MaisieNeural", "Female", "en-GB", "Maisie (child)"),
    ("en-IN-NeerjaNeural", "Female", "en-IN", "Neerja"),
    ("en-IN-PrabhatNeural", "Male", "en-IN", "Prabhat"),
    ("en-AU-NatashaNeural", "Female", "en-AU", "Natasha"),
    ("en-AU-WilliamNeural", "Male", "en-AU", "William"),
    ("en-CA-ClaraNeural", "Female", "en-CA", "Clara"),
    ("en-CA-LiamNeural", "Male", "en-CA", "Liam"),
    ("en-IE-EmilyNeural", "Female", "en-IE", "Emily"),
    ("en-IE-ConnorNeural", "Male", "en-IE", "Connor"),
    ("en-NZ-MollyNeural", "Female", "en-NZ", "Molly"),
    ("en-NZ-MitchellNeural", "Male", "en-NZ", "Mitchell"),
    ("en-ZA-LeahNeural", "Female", "en-ZA", "Leah"),
    ("en-ZA-LukeNeural", "Male", "en-ZA", "Luke"),
    ("en-SG-LunaNeural", "Female", "en-SG", "Luna"),
    ("en-SG-WayneNeural", "Male", "en-SG", "Wayne"),
    ("en-HK-YanNeural", "Female", "en-HK", "Yan"),
    ("en-HK-SamNeural", "Male", "en-HK", "Sam"),
    ("en-PH-RosaNeural", "Female", "en-PH", "Rosa"),
    ("en-PH-JamesNeural", "Male", "en-PH", "James"),
    ("en-NG-EzinneNeural", "Female", "en-NG", "Ezinne"),
    ("en-NG-AbeoNeural", "Male", "en-NG", "Abeo"),
    ("en-KE-AsiliaNeural", "Female", "en-KE", "Asilia"),
    ("en-KE-ChilembaNeural", "Male", "en-KE", "Chilemba"),
    # ---- Indian languages ----
    ("ta-IN-PallaviNeural", "Female", "ta-IN", "Pallavi"),
    ("ta-IN-ValluvarNeural", "Male", "ta-IN", "Valluvar"),
    ("ta-SG-VenbaNeural", "Female", "ta-SG", "Venba"),
    ("ta-SG-AnbuNeural", "Male", "ta-SG", "Anbu"),
    ("ta-LK-SaranyaNeural", "Female", "ta-LK", "Saranya"),
    ("ta-LK-KumarNeural", "Male", "ta-LK", "Kumar"),
    ("ta-MY-KaniNeural", "Female", "ta-MY", "Kani"),
    ("ta-MY-SuryaNeural", "Male", "ta-MY", "Surya"),
    ("hi-IN-SwaraNeural", "Female", "hi-IN", "Swara"),
    ("hi-IN-MadhurNeural", "Male", "hi-IN", "Madhur"),
    ("te-IN-ShrutiNeural", "Female", "te-IN", "Shruti"),
    ("te-IN-MohanNeural", "Male", "te-IN", "Mohan"),
    ("ml-IN-SobhanaNeural", "Female", "ml-IN", "Sobhana"),
    ("ml-IN-MidhunNeural", "Male", "ml-IN", "Midhun"),
    ("kn-IN-SapnaNeural", "Female", "kn-IN", "Sapna"),
    ("kn-IN-GaganNeural", "Male", "kn-IN", "Gagan"),
    ("mr-IN-AarohiNeural", "Female", "mr-IN", "Aarohi"),
    ("mr-IN-ManoharNeural", "Male", "mr-IN", "Manohar"),
    ("gu-IN-DhwaniNeural", "Female", "gu-IN", "Dhwani"),
    ("gu-IN-NiranjanNeural", "Male", "gu-IN", "Niranjan"),
    ("bn-IN-TanishaaNeural", "Female", "bn-IN", "Tanishaa"),
    ("bn-IN-BashkarNeural", "Male", "bn-IN", "Bashkar"),
    ("ur-IN-GulNeural", "Female", "ur-IN", "Gul"),
    ("ur-IN-SalmanNeural", "Male", "ur-IN", "Salman"),
    ("ne-NP-HemkalaNeural", "Female", "ne-NP", "Hemkala"),
    ("si-LK-ThiliniNeural", "Female", "si-LK", "Thilini"),
    # ---- Europe ----
    ("fr-FR-DeniseNeural", "Female", "fr-FR", "Denise"),
    ("fr-FR-HenriNeural", "Male", "fr-FR", "Henri"),
    ("de-DE-KatjaNeural", "Female", "de-DE", "Katja"),
    ("de-DE-ConradNeural", "Male", "de-DE", "Conrad"),
    ("es-ES-ElviraNeural", "Female", "es-ES", "Elvira"),
    ("es-ES-AlvaroNeural", "Male", "es-ES", "Alvaro"),
    ("es-MX-DaliaNeural", "Female", "es-MX", "Dalia"),
    ("es-MX-JorgeNeural", "Male", "es-MX", "Jorge"),
    ("it-IT-ElsaNeural", "Female", "it-IT", "Elsa"),
    ("it-IT-DiegoNeural", "Male", "it-IT", "Diego"),
    ("pt-BR-FranciscaNeural", "Female", "pt-BR", "Francisca"),
    ("pt-BR-AntonioNeural", "Male", "pt-BR", "Antonio"),
    ("nl-NL-FennaNeural", "Female", "nl-NL", "Fenna"),
    ("nl-NL-MaartenNeural", "Male", "nl-NL", "Maarten"),
    ("pl-PL-ZofiaNeural", "Female", "pl-PL", "Zofia"),
    ("pl-PL-MarekNeural", "Male", "pl-PL", "Marek"),
    ("sv-SE-SofieNeural", "Female", "sv-SE", "Sofie"),
    ("sv-SE-MattiasNeural", "Male", "sv-SE", "Mattias"),
    ("da-DK-ChristelNeural", "Female", "da-DK", "Christel"),
    ("nb-NO-PernilleNeural", "Female", "nb-NO", "Pernille"),
    ("fi-FI-NooraNeural", "Female", "fi-FI", "Noora"),
    ("cs-CZ-VlastaNeural", "Female", "cs-CZ", "Vlasta"),
    ("hu-HU-NoemiNeural", "Female", "hu-HU", "Noemi"),
    ("ro-RO-AlinaNeural", "Female", "ro-RO", "Alina"),
    ("el-GR-AthinaNeural", "Female", "el-GR", "Athina"),
    ("uk-UA-PolinaNeural", "Female", "uk-UA", "Polina"),
    ("ru-RU-SvetlanaNeural", "Female", "ru-RU", "Svetlana"),
    ("ru-RU-DmitryNeural", "Male", "ru-RU", "Dmitry"),
    ("tr-TR-EmelNeural", "Female", "tr-TR", "Emel"),
    ("tr-TR-AhmetNeural", "Male", "tr-TR", "Ahmet"),
    # ---- Asia / Middle East ----
    ("ja-JP-NanamiNeural", "Female", "ja-JP", "Nanami"),
    ("ja-JP-KeitaNeural", "Male", "ja-JP", "Keita"),
    ("ko-KR-SunHiNeural", "Female", "ko-KR", "Sun-Hi"),
    ("ko-KR-InJoonNeural", "Male", "ko-KR", "InJoon"),
    ("zh-CN-XiaoxiaoNeural", "Female", "zh-CN", "Xiaoxiao"),
    ("zh-CN-YunxiNeural", "Male", "zh-CN", "Yunxi"),
    ("zh-CN-YunyangNeural", "Male", "zh-CN", "Yunyang"),
    ("zh-TW-HsiaoChenNeural", "Female", "zh-TW", "HsiaoChen"),
    ("zh-HK-HiuMaanNeural", "Female", "zh-HK", "HiuMaan"),
    ("th-TH-PremwadeeNeural", "Female", "th-TH", "Premwadee"),
    ("vi-VN-HoaiMyNeural", "Female", "vi-VN", "HoaiMy"),
    ("id-ID-GadisNeural", "Female", "id-ID", "Gadis"),
    ("id-ID-ArdiNeural", "Male", "id-ID", "Ardi"),
    ("ms-MY-YasminNeural", "Female", "ms-MY", "Yasmin"),
    ("ar-SA-ZariyahNeural", "Female", "ar-SA", "Zariyah"),
    ("ar-SA-HamedNeural", "Male", "ar-SA", "Hamed"),
    ("ar-EG-SalmaNeural", "Female", "ar-EG", "Salma"),
    ("he-IL-HilaNeural", "Female", "he-IL", "Hila"),
    ("fa-IR-DilaraNeural", "Female", "fa-IR", "Dilara"),
]
